### ISSUE TITLE
Sub Menus

### ISSUE THREAD

**Issue by ben-styling** [theus/MenuChef#5]
Is there anything built in for sub menus?

If not, is this a feature you'd want for MenuChef, or would you want users to implement this per project?

**Comment by theus** [comment]
Hi @GoldenRust,

I think that it would be great this feature. But, must be compatible with actual version of MenuChef, dismissing a major version. Actually, the `<a>` elements are used as initial point. But this fact is easily solved by passing both `<a>` and `<li>`, to automatically identify sub menus. That is, you need to develop the internal compiler to make the interaction of submenus
